# This workflow will build a Java project with Gradle initially
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Simple Pipe 3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      myValues:
        description: 'Input Values'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - uses: actions/cache@v3
      id: cache-gradle
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#        restore-keys: |
#          ${{ runner.os }}-gradle-
    - if: ${{ steps.cache-gradle.outputs.cache-hit == 'true' }}
      name: Check for cache hit
      run: |
        echo "Got cache hit on key ${{ steps.cache-gradle.outputs.key }}"
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: greetings-jar
        path: build/libs
        
  test-run:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download candidate artifacts
      uses: actions/download-artifact@v2
      with:
        name: greetings-jar
    - shell: bash
      run: |
        java -jar greetings-actions.jar ${{ github.event.inputs.myValues }}
  
